[package]
name = "svm"
version = "0.1.0"
authors = ["merden"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = "1.1.0"
nom = "6"
colored = "2"